spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bridge_maintain?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: shanby123
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate: com.dancy.maintain.config.MySQL8TableType
    open-in-view: false


server:
  port: 8443